### ISSUE TITLE
Mac OS 9.0.4 on a Power Mac G3 Beige just freezes after this.

### ISSUE THREAD

**Issue by MesaBlack** [dingusdev/dingusppc#123]
![image](https://github.com/user-attachments/assets/09e054d1-a492-4ab6-a494-46f1b811a158)

I got this after a while:

> Emulator Error
> The emulator encountered an error:
> 
> Array buffer allocation failed

**Comment by dingusdev** [comment]
Looking at the error log shows this:

```
emulator-worker-CTy6jlUh.js:1 RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at Object.expandFileStorage (https://infinitemac.org/assets/dingusppc-Cq_lcOGO.js:3:3197)
    at Object.write (https://infinitemac.org/assets/dingusppc-Cq_lcOGO.js:3:5322)
    at Object.write (https://infinitemac.org/assets/dingusppc-Cq_lcOGO.js:3:18300)
    at Qt (https://infinitemac.org/assets/dingusppc-Cq_lcOGO.js:3:48350)
    at en (https://infinitemac.org/assets/dingusppc-Cq_lcOGO.js:3:48452)
    at dingusppc.wasm.__stdio_write (wasm://wasm/dingusppc.wasm-0064c4f6:wasm-function[2497]:0xd0ada)
    at dingusppc.wasm.fflush (wasm://wasm/dingusppc.wasm-0064c4f6:wasm-function[2493]:0xd05ba)
    at dingusppc.wasm.loguru::file_log(void*, loguru::Message const&) (wasm://wasm/dingusppc.wasm-0064c4f6:wasm-function[2467]:0xcdd58)
```

So, it seems some flushing is preventing this from working. Let me see if I can fix that.

**Comment by MesaBlack** [comment]
'k

**Comment by MesaBlack** [comment]
>     at Object.expandFileStorage (https://infinitemac.org/assets/dingusppc-Cq_lcOGO.js:3:3197)
>     at Object.write (https://infinitemac.org/assets/dingusppc-Cq_lcOGO.js:3:5322)
>     at Object.write (https://infinitemac.org/assets/dingusppc-Cq_lcOGO.js:3:18300)
>     at Qt (https://infinitemac.org/assets/dingusppc-Cq_lcOGO.js:3:48350)
>     at en (https://infinitemac.org/assets/dingusppc-Cq_lcOGO.js:3:48452)

Do we need contact with mihai?

**Comment by MesaBlack** [comment]
currently still freezes.

**Comment by dingusdev** [comment]
Confirmed infinite loop due to DMA issues:
```
heathrow.cpp:161 WARN| Unsupported DMA channel write, offset=0x700, val=0x200020
heathrow.cpp:137 WARN| Unsupported DMA channel read offset=0x704```

**Comment by dingusdev** [comment]
This has been fixed now. The latest alpha didn't have the fix in, but it is already present in the master tree.

<img width="647" height="491" alt="Image" src="https://github.com/user-attachments/assets/ab1aa784-3dee-422f-91cc-05019f6c6898" />
